# Generated by Django 4.2.11 on 2024-04-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobno', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='MainStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('subjects', models.CharField(max_length=100)),
                ('mobno', models.CharField(max_length=15)),
                ('parentsmobno', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('class_field', models.CharField(max_length=100)),
                ('timings', models.CharField(max_length=100)),
                ('feestatus', models.CharField(max_length=100)),
                ('totalclass', models.IntegerField()),
                ('attclass', models.IntegerField()),
                ('teachers', models.CharField(max_length=100)),
            ],
        ),
    ]
