# Generated by Django 4.2.11 on 2024-04-26 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aadmin',
            new_name='Admin',
        ),
    ]
