# Generated by Django 5.0 on 2024-04-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0009_teacher_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='par_mobile',
            field=models.CharField(default='+91', max_length=13),
        ),
    ]
