# Generated by Django 5.0 on 2024-05-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0010_student_par_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceChem11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=56)),
                ('username', models.CharField(default='unknown', max_length=56)),
                ('total_classes', models.CharField(default='unknown', max_length=56)),
                ('classes_attended', models.CharField(default='unknown', max_length=56)),
                ('mobile', models.CharField(default='+91', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceChem12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=56)),
                ('username', models.CharField(default='unknown', max_length=56)),
                ('total_classes', models.CharField(default='unknown', max_length=56)),
                ('classes_attended', models.CharField(default='unknown', max_length=56)),
                ('mobile', models.CharField(default='+91', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceCS11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=56)),
                ('username', models.CharField(default='unknown', max_length=56)),
                ('total_classes', models.CharField(default='unknown', max_length=56)),
                ('classes_attended', models.CharField(default='unknown', max_length=56)),
                ('mobile', models.CharField(default='+91', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceCS12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=56)),
                ('username', models.CharField(default='unknown', max_length=56)),
                ('total_classes', models.CharField(default='unknown', max_length=56)),
                ('classes_attended', models.CharField(default='unknown', max_length=56)),
                ('mobile', models.CharField(default='+91', max_length=13)),
            ],
        ),
    ]
