# Generated by Django 5.0 on 2024-05-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0011_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=56)),
                ('username', models.CharField(max_length=56)),
                ('clas', models.CharField(max_length=56)),
                ('subjects', models.TextField(max_length=256)),
                ('mobile', models.CharField(default='+91', max_length=13)),
                ('par_mobile', models.CharField(default='+91', max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('topic', models.CharField(default='unknown', max_length=56)),
                ('marks_total', models.CharField(max_length=13)),
                ('marks_obtained', models.CharField(max_length=13)),
                ('remark', models.CharField(default='unknown', max_length=56)),
            ],
        ),
        migrations.DeleteModel(
            name='Marks',
        ),
    ]
