# Generated by Django 5.0 on 2024-05-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0011_attendancechem11_attendancechem12_attendancecs11_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancechem11',
            name='absent_days',
            field=models.CharField(default='unknown', max_length=56),
        ),
        migrations.AddField(
            model_name='attendancechem12',
            name='absent_days',
            field=models.CharField(default='unknown', max_length=56),
        ),
        migrations.AddField(
            model_name='attendancecs11',
            name='absent_days',
            field=models.CharField(default='unknown', max_length=56),
        ),
        migrations.AddField(
            model_name='attendancecs12',
            name='absent_days',
            field=models.CharField(default='unknown', max_length=56),
        ),
    ]
