# Generated by Django 5.0 on 2024-05-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0012_attendancechem11_absent_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancechem11',
            name='subject',
            field=models.CharField(default='unknown', max_length=56),
        ),
        migrations.AddField(
            model_name='attendancechem12',
            name='subject',
            field=models.CharField(default='unknown', max_length=56),
        ),
        migrations.AddField(
            model_name='attendancecs11',
            name='subject',
            field=models.CharField(default='unknown', max_length=56),
        ),
        migrations.AddField(
            model_name='attendancecs12',
            name='subject',
            field=models.CharField(default='unknown', max_length=56),
        ),
    ]
