# Generated by Django 4.2.11 on 2024-05-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0013_attendancechem11_subject_attendancechem12_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancechem11',
            name='name',
            field=models.CharField(max_length=56),
        ),
    ]
