# Generated by Django 5.0 on 2024-05-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0014_alter_attendancechem11_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancechem11',
            name='absent_date',
            field=models.CharField(default='unknown', max_length=56),
        ),
    ]
