# Generated by Django 5.0 on 2024-05-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0017_alter_attendancechem11_absent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancechem12',
            name='absent_date',
            field=models.CharField(default='unknown', max_length=56),
        ),
        migrations.AddField(
            model_name='attendancecs11',
            name='absent_date',
            field=models.CharField(default='unknown', max_length=56),
        ),
        migrations.AddField(
            model_name='attendancecs12',
            name='absent_date',
            field=models.CharField(default='unknown', max_length=56),
        ),
        migrations.AlterField(
            model_name='attendancechem11',
            name='absent_date',
            field=models.CharField(default='unknown', max_length=56),
        ),
    ]
