# Generated by Django 4.2.11 on 2024-05-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0018_attendancechem12_absent_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarksChem11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=56)),
                ('subject', models.CharField(default='unknown', max_length=56)),
                ('username', models.CharField(default='unknown', max_length=56)),
                ('total_marks', models.CharField(default='unknown', max_length=56)),
                ('marks_obtained', models.CharField(default='unknown', max_length=56)),
                ('remarks', models.CharField(default='unknown', max_length=56)),
                ('mobile', models.CharField(default='+91', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='MarksChem12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=56)),
                ('subject', models.CharField(default='unknown', max_length=56)),
                ('username', models.CharField(default='unknown', max_length=56)),
                ('total_marks', models.CharField(default='unknown', max_length=56)),
                ('marks_obtained', models.CharField(default='unknown', max_length=56)),
                ('remarks', models.CharField(default='unknown', max_length=56)),
                ('mobile', models.CharField(default='+91', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='MarksCS11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=56)),
                ('subject', models.CharField(default='unknown', max_length=56)),
                ('username', models.CharField(default='unknown', max_length=56)),
                ('total_marks', models.CharField(default='unknown', max_length=56)),
                ('marks_obtained', models.CharField(default='unknown', max_length=56)),
                ('remarks', models.CharField(default='unknown', max_length=56)),
                ('mobile', models.CharField(default='+91', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='MarksCS12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=56)),
                ('subject', models.CharField(default='unknown', max_length=56)),
                ('username', models.CharField(default='unknown', max_length=56)),
                ('total_marks', models.CharField(default='unknown', max_length=56)),
                ('marks_obtained', models.CharField(default='unknown', max_length=56)),
                ('remarks', models.CharField(default='unknown', max_length=56)),
                ('mobile', models.CharField(default='+91', max_length=13)),
            ],
        ),
        migrations.RemoveField(
            model_name='attendancechem11',
            name='absent_date',
        ),
        migrations.RemoveField(
            model_name='attendancechem12',
            name='absent_date',
        ),
        migrations.RemoveField(
            model_name='attendancecs11',
            name='absent_date',
        ),
        migrations.RemoveField(
            model_name='attendancecs12',
            name='absent_date',
        ),
    ]
