# Generated by Django 5.0 on 2024-05-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0019_markschem11_markschem12_markscs11_markscs12_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancechem11',
            name='absent_date',
            field=models.CharField(default='unknown', max_length=56),
        ),
        migrations.AddField(
            model_name='attendancechem12',
            name='absent_date',
            field=models.CharField(default='unknown', max_length=56),
        ),
        migrations.AddField(
            model_name='attendancecs11',
            name='absent_date',
            field=models.CharField(default='unknown', max_length=56),
        ),
        migrations.AddField(
            model_name='attendancecs12',
            name='absent_date',
            field=models.CharField(default='unknown', max_length=56),
        ),
    ]
