# Generated by Django 5.0 on 2024-05-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0020_markschem11_title_markschem12_title_markscs11_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markschem11',
            name='title',
        ),
        migrations.RemoveField(
            model_name='markschem12',
            name='title',
        ),
        migrations.RemoveField(
            model_name='markscs11',
            name='title',
        ),
        migrations.RemoveField(
            model_name='markscs12',
            name='title',
        ),
        migrations.AddField(
            model_name='attendancechem11',
            name='absent_date',
            field=models.CharField(default='unknown', max_length=56),
        ),
        migrations.AddField(
            model_name='attendancechem12',
            name='absent_date',
            field=models.CharField(default='unknown', max_length=56),
        ),
        migrations.AddField(
            model_name='attendancecs11',
            name='absent_date',
            field=models.CharField(default='unknown', max_length=56),
        ),
        migrations.AddField(
            model_name='attendancecs12',
            name='absent_date',
            field=models.CharField(default='unknown', max_length=56),
        ),
    ]
