# Generated by Django 5.0 on 2024-05-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0022_markschem11_title_markschem12_title_markscs11_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fees',
            field=models.CharField(default='paid', max_length=56),
        ),
    ]
