# Generated by Django 5.0 on 2024-06-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0023_student_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='unknown', max_length=56),
        ),
        migrations.AddField(
            model_name='teacher',
            name='username',
            field=models.CharField(default='unknown', max_length=56),
        ),
    ]
