# Generated by Django 5.0 on 2024-07-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0024_teacher_password_teacher_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lectures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('chapter', models.CharField(max_length=200)),
                ('class_name', models.CharField(choices=[('11', 'Class 11'), ('12', 'Class 12')], max_length=2)),
                ('video_url', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Lectures',
            },
        ),
    ]
